
on:
  push:
    branches: [ main ]
    tags: [ '*.*' ]
  pull_request:
    branches: [ main ]

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]
        R: [ '4.0', '4.1', '4.2' ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.R }}
          rtools-version: '42'

      - uses: r-lib/actions/setup-r-dependencies@v2

      - run: |
          cd ..; R CMD INSTALL --build FunQuant
          NAME=`ls FunQuant_*.*`
          mv $NAME FunQuant/R_${{ matrix.R }}-$NAME
        shell: bash
        name: R CMD INSTALL
        
      - uses: actions/upload-artifact@v2
        with:
          path: ./R_*

      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./R_*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
